### ISSUE TITLE
duplicate calls if more than one instance in row

### ISSUE THREAD

**Issue by arievanden** [dmstr/yii2-ajax-button#1]
Hello,

I implemented your ajax plugin and it works great! I did run into a problem when I'm using more than one ajax button per row when the button labels are different. 

This is called from a GridView::widget, running latest Yii2 & php7.

When I generate 2 buttons for a single row like this:

return dmstr\ajaxbutton\AjaxButton::widget([
    'method' => 'get',
    'params' => ['id' => $model->applic_field_id],
    'url' => [$url_call],
    'content' => "AAA", //<--I CAN HAVE AS MANY IDENTICAL "AAA" AS I WANT
    'options' => ['class' => $label_class]
]);

return dmstr\ajaxbutton\AjaxButton::widget([
    'method' => 'get',
    'params' => ['id' => $model->applic_field_id],
    'url' => [$url_call],
    'content' => "BBB", //<-- THIS CAUSES THE 2ND AJAX CALL
    'options' => ['class' => $label_class]
]);

it generates TWO instances of the .on('click'). So it fires ajax twice with each button click. I'm not sure if I"m doing something wrong or need to add a param to the call so it doesn't create two instances of this. Thank you!

$(document).on('click','button[data-ajax-button-id]', 'click', function() {
    var button = $(this);
    $.ajax({
        url : button.data('ajax-button-url'),
        type : button.data('ajax-button-method'),
        data : button.data('ajax-button-params'),        
    });
});
$(document).on('click','button[data-ajax-button-id]', 'click', function() {
    var button = $(this);
    $.ajax({
        url : button.data('ajax-button-url'),
        type : button.data('ajax-button-method'),
        data : button.data('ajax-button-params'),        
    });
});

**Comment by schmunk42** [comment]
I just had a quick look, but I think you need to use different IDs, and bind only one event-listener to each button.

**Comment by arievanden** [comment]
Hello. I'm still have a problem where when I generate two ajax buttons for different purposes (ie. bookmark item toggle and add item to cart), pointing to two distinct URLs, it generates:
$(document).on('click','button[data-ajax-button-id]', 'click', function(){...} two times. This is fine.

But now when I click button A, it fires twice calling URL A twice. Click B, and it fires twice calling URL B twice. How can I generate the buttons so it only fires once for each? Sorry, my js skills could be better.

Adding e.stopImmediatePropagation(); does prevent the second one from firing, but it also stops the "success" callback functions after the initial ajax function. So I'm not sure what to do at this point.

**Comment by arievanden** [comment]
I think I may have found a solution. For button group A, add a unique button class value such as "group_a".

public $group_class_id; // declare group class var

// $(document).on('click','button[data-ajax-button-id]', 'click', function() {} //replaced with:
$('button.{$this->group_class_id').click(function() {}

public function init()
    {
        parent::init();
        $this->registerAssets();
        $this->options['id'] = $this->id; // added for good measure, but probably not needed
        $this->options['data-ajax-button-id'] = $this->id;
        $this->options['data-ajax-button-method'] = $this->method;
        $this->options['data-ajax-button-params'] = $this->params;
        $this->options['data-ajax-button-url'] = Url::to($this->url);
    }

For calling:
$follow_button = \dmstr\ajaxbutton\AjaxButton::widget([
            'method' => 'post',
            'params' => $post_params,
            'url' => [$function_call],
            'group_class_id' => $group_class_id,  //includes "group_a"
            'content' => $label,
            'options' => ['class' => 'group_a btn-info'],  //includes "group_a"
            ...

**Comment by schmunk42** [comment]
So we can close this?
